#!/usr/bin/perl

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::Build::CreateLinks  qw(:all);


event_actions('nethserver-adagios-update', qw(
   initialize-default-databases 00
   nethserver-adagios-conf 30
   nethserver-adagios-ldapauth 40
));

event_templates('nethserver-adagios-update', qw(
   /etc/httpd/conf.d/adagios.conf
   /etc/httpd/conf.d/nagios.conf
   /etc/httpd/conf.d/pnp4nagios.conf
   /usr/share/okconfig/client/windows/nsclient/datafiles/allowed_hosts.ini
));

event_services('nethserver-adagios-update', qw(
   npcd restart
   nrpe restart
   nagios restart
   httpd restart
   xinetd reload
));

event_actions('runlevel-adjust', qw(
   nethserver-adagios-firstcommit 90
));


event_templates('interface-update', qw(
   /usr/share/okconfig/client/windows/nsclient/datafiles/allowed_hosts.ini
));

